### ISSUE TITLE
Import error in config.py

### ISSUE THREAD

**Issue by scfleming** [gphoton-tools/ggui#6]
ImportError: ('Error loading config file /Users/fleming/Work/GALEX/gPhoton/gphoton-tools/ggui/config.py:\nImporting PyQt5 forbidden by glue.external.qt'

In v0.2.2, in my environment I get this error.  This might be related to this issue:
http://glueviz.org/en/stable/developer_guide/qt_development.html

I.e., don't specify a specific PyQt in imports...

**Comment by scfleming** [comment]
E.g., this seems to work without error:

from qtpy.QtWidgets import QFileDialog

**Comment by duytnguyendtn** [comment]
QtPy appears to be an abstraction layer for API calls to PyQt. This is to maintain compatibility with any updates to the Qt libraries. Changed in local and will push after addressing Issue #7
